version: '3.7'

services:
  web:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    command: /bin/bash -c "python twilio_v0/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/twilio_v0
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
